// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKQ840giDWWrP2tt_37cCZtJOONJmIRD8',
    appId: '1:1035745821086:web:0a6ce3f8bf414a988a968f',
    messagingSenderId: '1035745821086',
    projectId: 'test-96b7b',
    authDomain: 'test-96b7b.firebaseapp.com',
    storageBucket: 'test-96b7b.firebasestorage.app',
    measurementId: 'G-P7NJW563LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApfDVQRCsSM_C1nYYgKQFpZ8MLLcNT_oQ',
    appId: '1:1035745821086:android:dc88d1166a2a56018a968f',
    messagingSenderId: '1035745821086',
    projectId: 'test-96b7b',
    storageBucket: 'test-96b7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu7pOA45eRqXc3tJtkHcM3R3GFwNVXrKY',
    appId: '1:1035745821086:ios:12481a45fbcaf6cf8a968f',
    messagingSenderId: '1035745821086',
    projectId: 'test-96b7b',
    storageBucket: 'test-96b7b.firebasestorage.app',
    androidClientId: '1035745821086-d8jfouglhjjtt9mkrcrvlun5147u4mkl.apps.googleusercontent.com',
    iosClientId: '1035745821086-uvlhi26r1atqvbfin782okbcibbq03i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu7pOA45eRqXc3tJtkHcM3R3GFwNVXrKY',
    appId: '1:1035745821086:ios:12481a45fbcaf6cf8a968f',
    messagingSenderId: '1035745821086',
    projectId: 'test-96b7b',
    storageBucket: 'test-96b7b.firebasestorage.app',
    androidClientId: '1035745821086-d8jfouglhjjtt9mkrcrvlun5147u4mkl.apps.googleusercontent.com',
    iosClientId: '1035745821086-uvlhi26r1atqvbfin782okbcibbq03i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKQ840giDWWrP2tt_37cCZtJOONJmIRD8',
    appId: '1:1035745821086:web:f481b3083b7cf87d8a968f',
    messagingSenderId: '1035745821086',
    projectId: 'test-96b7b',
    authDomain: 'test-96b7b.firebaseapp.com',
    storageBucket: 'test-96b7b.firebasestorage.app',
    measurementId: 'G-S7PG30TTC0',
  );

}